name: App Engine Deploy

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
    deploy:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v4

      - name: Authenticate
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_DEPLOY_SA_KEY }}'

      - name: Deploy to app engine
        id: deploy
        uses: google-github-actions/deploy-appengine@v1
        with:
          deliverables: app.yaml

      - name: Check that application is up
        run: curl "${{ steps.deploy.outputs.url }}/hello/test"
