name: App Engine Deploy

# TODO revert this
#on:
#  push:
#    tags:
#      - "v*"
#  workflow_dispatch:

on:
    push:
        branches: ["**"]
    workflow_dispatch:  

jobs:
    deploy:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2

      - name: Authenticate
        id: auth
        uses: google-github-actions/auth@v0.8.0
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Deploy to app engine
        id: deploy
        uses: google-github-actions/deploy-appengine@v0.8.0
        with:
          deliverables: app.yaml

      - name: Check that application is up
        run: curl "${{ steps.deploy.outputs.url }}/hello/test"
