name: App Engine Deploy

# TODO revert this
#on:
#  push:
#    tags:
#      - "v*"
#  workflow_dispatch:

on:
    push:
        branches: ["**"]
    workflow_dispatch:  

jobs:
    deploy:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
      
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account: ${{ secrets.GCP_SA }}
          export_default_credentials: true

      - name: Deploy to app engine
        id: deploy
        uses: google-github-actions/deploy-appengine@v0.4.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          deliverables: app.yaml

      - name: Check that application is up
        run: curl "${{ steps.deploy.outputs.url }}/hello/test"
