name: Build

on:
    push:
        branches: ["**"]
    workflow_dispatch:

jobs:
    node-build:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci

    docker-build:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: false
          tags: "${{ github.repository }}:${{ github.sha }}"
